### ISSUE TITLE
Children not re-rendering upon state change?

### ISSUE THREAD

**Issue by DavideValdo** [Bhoos/react-native-coverflow#1]
This the behaviour: https://giphy.com/gifs/xUPGcAd4NctowQAzsc
As you can see, triggering a re-render seems not to be working and the star button remains the same color, unless I change the current selected segment.

This is how I'm managing state:
1. My _PictureThumb_ component changes the "Model" which emit events
2. My _Gallery_ component listens to the event and correctly updates internal state through setState();

Updated products (with a new or nulled bookmarkID) are mapped to every _PictureThumb_'s props. Methods from the _Gallery_ component:

```
  _renderGallery () 
    gallery = new Array();

    this.state.products.map((p) => {
      gallery.push(
        <PictureThumb product={p} />
      );
    });

    return gallery;
  }

_showAllProducts () {
    return (
        <ScrollView>
            <View style={{flex: 1, flexWrap: 'wrap', flexDirection: 'row'}}>
               {this._renderGallery()}
            </View>
        </ScrollView>
    )
  }
```

This is the 'FEATURED' part, that gets correctly re-rendered only if I change segment:

```
 _renderFeaturedGallery () {
    console.debug("Rerendering coverflow with state", this.state.products);
    gallery = new Array();

    this.state.products.filter((p) => {return p.featured}).map((p) => {
      gallery.push(<PictureThumb product={p} />);
    })

    return gallery;
  }

_showFeatured () {
    return (
      <Coverflow style={{marginTop: 20}} onChange={(index) => {}}>
        {this._renderFeaturedGallery()}
      </Coverflow>
    )
  }
```
**_renderFeaturedGallery() launches console.debug("Rerendering coverflow with state", this.state.products), which shows the correctly updated state!**

So, is it not re-rendering because of the component?

**Comment by syaau** [comment]
The Coverflow style needs to define its size. Can you try putting a flex: 1 (or a width, height) for the Coverflow style.

**Comment by syaau** [comment]
sorry, the gif just loaded, and I understood your problem. Give me a moment.

**Comment by syaau** [comment]
Can you share me the PictureThumb component ?

**Comment by syaau** [comment]
Also, you need to provide a unique "key" attribute whenever you are passing children via an array.

**Comment by DavideValdo** [comment]
PictureThumb component:

```
import React, { Component } from 'react';
import { View, Image, Dimensions, TouchableOpacity, StyleSheet } from 'react-native';
import { Actions } from 'react-native-router-flux';
import CachedImage from 'react-native-cached-image';
import Info from './_Info.js';

export default class PictureThumb extends Component {
  constructor (props) {
    super(props);
  }

  hasBookmark () {
    return this.props.product.bookmarkID != null;
  }

  _toggleBookmark = async () => {
    if (this.hasBookmark()) {
      await Info.removeBookmark(this.props.product.bookmarkID);
    }
    else {
      outcome = await Info.addBookmark('product', this.props.product.id);
      /* User is anonymous */
      if (!outcome)
        Actions.register();
    }
  }

  _renderZoomButton ()  {
    return (
      <TouchableOpacity>
        <Image style={styles.button} source={require ('../assets/zoom-product.png')} />
      </TouchableOpacity>
    )
  }

  _renderBookmarkButton () {
    return (
      <TouchableOpacity onPress={this._toggleBookmark}>
        {
          this.hasBookmark() ?
          <Image style={styles.button} source={require ('../assets/bookmark-product-active.png')} /> :
          <Image style={styles.button} source={require ('../assets/bookmark-product.png')} />
        }
      </TouchableOpacity>
    )
  }

  render () {
      return (
        <View style={this.props.wrapperStyle}>
          <CachedImage style={styles.thumb} source={{uri: this.props.product.url}}>
              {this._renderZoomButton()}
              {this._renderBookmarkButton()}
          </CachedImage>
        </View>
      )
  }
}

styles = StyleSheet.create({
  button: {
    width: 40,
    height: 40,
    margin: 5
  },
  thumb: {
    flex: 1, 
    width: null, 
    alignSelf: 'stretch', 
    flexDirection: 'row', 
    alignItems: 'center', 
    justifyContent: 'center'
  }
})
```

**Comment by syaau** [comment]
While pushing your PictureThumb in the array, try adding key={the product id} attribute.

**Comment by DavideValdo** [comment]
Done correctly. Still won't re-render.

**Comment by syaau** [comment]
Does the book mark state toggle in the all products section as well ?

**Comment by syaau** [comment]
In your toggle method, after your Info.removeBookmark there is no setState. Try doing a this.forceUpdate after the removal. A quick hack to change the state.

**Comment by DavideValdo** [comment]
The parent component is listening for an event

```
componentDidMount () {
    /* Sync bookmark state, gets passed to PictureThumb props */
    _EventsReceiver_.register('onBookmarkChanged', (action) => {
      newState = Reducers.syncBookmarks(this.state.products, action);      
      this.setState({
        products: newState
      });
    });
  }
```

This triggers  _renderFeaturedGallery() where console.debug() outputs the correct updated state

**Comment by syaau** [comment]
Can you share the project, I can try debugging on my machine and figure out the problem.

**Comment by DavideValdo** [comment]
I added you on a repo

**Comment by syaau** [comment]
I am getting a "Print: Entry, ":CFBundleIdentifier", Does Not Exist". Did you have this problem ?

**Comment by syaau** [comment]
Looks like GoogleService-Info.plist file is missing

**Comment by DavideValdo** [comment]
Try now
Can you give me any IM contact?

**Comment by syaau** [comment]
skype ma at ranjan.newa

**Comment by hugoh59** [comment]
Same issue here
