### ISSUE TITLE
Cannot be wrapped by View component

### ISSUE THREAD

**Issue by qiwwwwwww** [Bhoos/react-native-coverflow#12]
Hi, thanks for this wonderful component. 
However, there's a issue occurring when I use it. 
It will disappear when I use `<View><Coverflow /></View>`. However, it will be fine if I use `<Coverflow/>` purely. 
Any ideas?

**Comment by syaau** [comment]
It's most likely because the View doesn't have any style.so it must have
collapsed.

**Comment by qiwwwwwww** [comment]
Sorry, but I do have styles for View, and it still doesnt work

**Comment by qiwwwwwww** [comment]
Hey here is what I have for demo, could you please take a look?
https://snack.expo.io/rJp3M0cmX

**Comment by syaau** [comment]
@Lyra007 I don't know why but the alignments had created the problem, I just kept flex: 1 and it worked normally. I will look into this some time later, but I think you should be able to work with this.

https://snack.expo.io/B1T4qC97m
