### ISSUE TITLE
<<Cannot read property 'instanceOf' of undefined>> after upgrade

### ISSUE THREAD

**Issue by DavideValdo** [Bhoos/react-native-coverflow#6]
After upgrading to React Native 0.49 I get this:

![screen shot 2017-10-16 at 22 48 43](https://user-images.githubusercontent.com/26572302/31634585-58fb32fa-b2c4-11e7-8293-938a540f7abb.png)

**Comment by syaau** [comment]
This seems to be due to PropTypes being used separately and removed from React. Please use react-native-coverflow@0.1.6. The issue must be resolved.
